// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATHF4ror0XVKGGtRQmGiaK6oTK4Nt_R_4',
    appId: '1:690474689860:web:1519f95a9a5b3272592311',
    messagingSenderId: '690474689860',
    projectId: 'budget-manager-df134',
    authDomain: 'budget-manager-df134.firebaseapp.com',
    storageBucket: 'budget-manager-df134.appspot.com',
    measurementId: 'G-EN7R6Z9L2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN73uAZ7yfSeakDdawMardz-bP94AMdfk',
    appId: '1:690474689860:android:04b1eb6333dc9f1c592311',
    messagingSenderId: '690474689860',
    projectId: 'budget-manager-df134',
    storageBucket: 'budget-manager-df134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX9pCduN6Vqnn9kdgUMJe8JhQb0XhxT6w',
    appId: '1:690474689860:ios:1c9208bd9e5f2d2c592311',
    messagingSenderId: '690474689860',
    projectId: 'budget-manager-df134',
    storageBucket: 'budget-manager-df134.appspot.com',
    iosClientId: '690474689860-2a4sd304blrkrneroav2q0jequ4lr0ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX9pCduN6Vqnn9kdgUMJe8JhQb0XhxT6w',
    appId: '1:690474689860:ios:1c9208bd9e5f2d2c592311',
    messagingSenderId: '690474689860',
    projectId: 'budget-manager-df134',
    storageBucket: 'budget-manager-df134.appspot.com',
    iosClientId: '690474689860-2a4sd304blrkrneroav2q0jequ4lr0ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetManager',
  );
}
